[package]
name = "lto_statistics"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
octocrab = "0.39.0"
tokio = { version = "1.40.0", features = ["full"] }

[profile.release]
lto = true
